feat(backend): Configuring GridFs in spring boot application for hand…
stephane-segning/lynx-scanner-backend pull request #17
Opened 2024-04-25 15:16 UTC by mbunwe-victor

2024-04-25 15:35 UTC, bryandino673 approved these changes

2024-04-25 15:45 UTC, Christiantyemele reviewed
@stephane-segning and @mbunwe-victor i think this should have a DBObject which will implement store methods

2024-04-25 16:08 UTC, mbunwe-victor commented
> @stephane-segning and @mbunwe-victor i think this should have a DBObject which will implement store methods

@Christiantyemele, the implementation of GridFsTemplate handles everything that has to do with the store method.The GridFsTemplate encapsulates the functionality needed to interact with GridFS for file storage

2024-04-25 18:37 UTC, ValantineSuh approved these changes

2024-04-26 06:31 UTC, stephane-segning requested changes
Please write some unit tests and integration tests to ensure this is working

2024-04-29 14:12 UTC, mbunwe-victor commented
> Please write some unit tests and integration tests to ensure this is working

Done

2024-04-29 15:23 UTC, ValantineSuh approved these changes
Looks good!

2024-05-02 19:53 UTC, stephane-segning requested changes

2024-05-02 19:53 UTC, stephane-segning commented on src/test/java/com/ssegning/lynx/lynxbackend/GridFsConfigurationTest.java
> +    }
This is not testing something. Remove this test

2024-05-02 19:53 UTC, stephane-segning commented on src/test/java/com/ssegning/lynx/lynxbackend/GridFsConfigurationTest.java
This test case is not useful. Please remove it

2024-05-03 09:10 UTC, mbunwe-victor commented on src/test/java/com/ssegning/lynx/lynxbackend/GridFsConfigurationTest.java
I have remove the GridFsConfigurationTest.java

2024-05-03 15:47 UTC, stephane-segning approved these changes

2024-05-03 16:00 UTC, Christiantyemele approved these changes

2024-05-03 16:14 UTC, merged