feat(backend): Generate APIs on the backend using openapi
stephane-segning/lynx-scanner-backend pull request #26
Opened 2024-05-02 19:29 UTC by nancymuyeh

Generate API on the backend using openApiGenerate gradle task #15

2024-05-02 19:46 UTC, stephane-segning requested changes
Good work! Make sure now that the build process depends on the OpenAPI generation

2024-05-03 09:40 UTC, nancymuyeh commented
> Good work! Make sure now that the build process depends on the OpenAPI generation

Done

2024-05-03 09:43 UTC, Koufan-De-King approved these changes

2024-05-03 15:46 UTC, stephane-segning requested changes

2024-05-03 15:46 UTC, stephane-segning commented on build.gradle
> +task customBuild {
Don't use a custom build, but the normal build

2024-05-04 06:51 UTC, stephane-segning requested changes

2024-05-04 06:51 UTC, stephane-segning commented on build.gradle
> +tasks.named("openApiGenerate") { dependsOn("build") }
Good but the opposite. It's the build that should depends on the openapi generation.

2024-05-04 14:02 UTC, stephane-segning approved these changes

2024-05-04 16:22 UTC, mbunwe-victor approved these changes
Good work

2024-05-04 16:43 UTC, stephane-segning commented
The pipeline is failing. This can be due to the fact that the submodule is not downloaded. Try updating the GitHub Workflow file accordingly

2024-05-06 09:05 UTC, stephane-segning requested changes
Update the CI to pull the git submodules too

2024-05-06 10:31 UTC, nancymuyeh commented
> Update the CI to pull the git submodules too

Done Everything looks good now

2024-05-06 16:05 UTC, Bansikah approved these changes
Great work @nancymuyeh

2024-05-06 20:27 UTC, stephane-segning approved these changes

2024-05-07 06:34 UTC, merged