feat: removed mongofs and added graalvm
stephane-segning/lynx-scanner-backend pull request #31
Opened 2024-06-25 23:00 UTC by stephane-segning

2024-06-27 07:25 UTC, mbunwe-victor requested changes
Sir @stephane-segning most of the builds are not passing please check them out.

2024-06-27 14:56 UTC, nancymuyeh requested changes
Well done adding graalvm to the project, seems good

2024-06-27 14:56 UTC, nancymuyeh commented on src/main/java/com/ssegning/lynx/lynxbackend/controller/FileApiImpl.java
This implements an interface FileApi which does not exist and is causing the build to fail also making the workflow to fail . So you should do something about it

2024-06-28 00:52 UTC, stephane-segning commented
> Sir @stephane-segning most of the builds are not passing please check them out.

Done!

2024-06-28 00:59 UTC, stephane-segning commented on src/main/java/com/ssegning/lynx/lynxbackend/controller/FileApiImpl.java
This was because of the frontend not well being loaded. Fixed now

2024-06-29 23:26 UTC, merged